pipeline:
  test:
    image: maven:3-jdk-8
    commands:
      - export CI="true"
      - mvn clean compile test-compile
      - mvn exec:java@setUpFactoryDb
      - mvn exec:java@setUpGarageDb
      - mvn cobertura:cobertura || echo ""
      - curl -s https://codecov.io/bash | bash
